add Strata to summariseClinicalRecords()
oxford-pharmacoepi/OmopSketch pull request #114
Opened 2024-09-16 10:39 UTC by martaalcalde

2024-09-16 14:13 UTC, martaalcalde commented
Fixes #68

2024-09-17 09:40 UTC, catalamarti requested changes

2024-09-17 09:40 UTC, catalamarti commented on R/summariseInObservation.R
> +      dplyr::compute(name = "demographicsTable", temporary = FALSE)
use always lowercase names

2024-09-17 09:40 UTC, catalamarti commented on R/summariseRecordCount.R
> +  if((omopTable |> dplyr::select("person_id") |> dplyr::anti_join(cdm[["person"]], by = "person_id") |> dplyr::tally() |> dplyr::pull("n")) != 0){
use utils::head(1) to be faster

2024-09-18 07:58 UTC, catalamarti approved these changes

2024-09-18 07:58 UTC, merged