summariseOmopTable() release
oxford-pharmacoepi/OmopSketch pull request #13
Opened 2024-06-10 12:22 UTC by martaalcalde

2024-06-10 14:49 UTC, catalamarti requested changes
great job @martaalcalde just a few comments, lets discuss in person if sth is not clear

2024-06-10 14:49 UTC, catalamarti commented on R/summariseOmopTable.R
> +#' @param sourceVocabulary Whether to summarise source concept.
#' @param sourceVocabulary Whether to summarise source concept vocabulary.

2024-06-10 14:49 UTC, catalamarti commented on R/summariseOmopTable.R
> +    if(standardConcept){
for the ones that the default is true add:
`if (standardConcept && missing(standardConcept))`
so the warning is only displayed if the user explicitly set it to TRUE

2024-06-10 14:49 UTC, catalamarti commented on R/summariseOmopTable.R
> +    cli::cli_abort(paste0(omopgenerics::tableName(omopTable), " omop table is empty."))
can we just throw a warning a return an empty result?
In principle the error is for when the inputs are not correctly populated

2024-06-10 14:49 UTC, catalamarti commented on R/summariseOmopTable.R
> +      dplyr::full_join(
why full_join?

2024-06-10 14:49 UTC, catalamarti commented on R/summariseOmopTable.R
> +    dplyr::n_distinct()
Avoid collecting all the person ids:
```
cdm[["person"]] |>
  dplyr::ungroup() |>
  dplyr::summarise(x = dplyr::n_distinct(.data$person_id)) |>
  dplyr::pull("x") |>
  as.integer()
```

2024-06-10 14:49 UTC, catalamarti commented on R/summariseOmopTable.R
> +      "estimate_value" = as.character(omopTable |> dplyr::pull(.data$person_id) |> dplyr::n_distinct())
same than previous comment

2024-06-10 14:49 UTC, catalamarti commented on R/summariseOmopTable.R
> +      "estimate_value" = as.character(omopTable |> dplyr::tally() |> dplyr::pull(.data$n))
I think it must be pull("n")

2024-06-10 14:49 UTC, catalamarti commented on R/summariseOmopTable.R
> +        100* (omopTable |> dplyr::pull(.data$person_id) |> dplyr::n_distinct()) / .env$people
same previous comments

2024-06-10 14:49 UTC, catalamarti commented on R/summariseOmopTable.R
> +    "end_date"   = endDate(name),
what happens if endDate is NA?

2024-06-10 14:49 UTC, catalamarti commented on R/summariseOmopTable.R
> +              .data$end_date <= .data$obs_end
I thought we would sumarise in observation start_date and in observation end date separately

2024-06-10 15:28 UTC, martaalcalde commented on R/summariseOmopTable.R
> +      dplyr::full_join(
use bind rows

2024-06-11 08:22 UTC, martaalcalde commented
Changes implemented in #14

2024-06-11 08:24 UTC, merged